[[dependencies]]
name = "aead"
version = "0.5.2"
description = """
Traits for Authenticated Encryption with Associated Data (AEAD) algorithms,
such as AES-GCM as ChaCha20Poly1305, which provide a high-level API
"""
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2019 MobileCoin, LLC",
  "Copyright (c) 2019 The RustCrypto Project Developers",
]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/traits"

[[dependencies]]
name = "aes"
version = "0.8.4"
description = "Pure Rust implementation of the Advanced Encryption Standard (a.k.a. Rijndael)"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2018 Artyom Pavlov"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/block-ciphers"

[[dependencies]]
name = "aes-gcm"
version = "0.10.3"
description = """
Pure Rust implementation of the AES-GCM (Galois/Counter Mode)
Authenticated Encryption with Associated Data (AEAD) Cipher
with optional architecture-specific hardware acceleration
"""
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2019 The RustCrypto Project Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/AEADs"

[[dependencies]]
name = "base64"
version = "0.22.0"
description = "encodes and decodes base64 as bytes or utf8"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015 Alice Maz"]
authors = [
  "Alice Maz <alice@alicemaz.com>",
  "Marshall Pierce <marshall@mpierce.org>",
]
repository = "https://github.com/marshallpierce/rust-base64"

[[dependencies]]
name = "base64ct"
version = "1.6.0"
description = """
Pure Rust implementation of Base64 (RFC 4648) which avoids any usages of
data-dependent branches/LUTs and thereby provides portable \"best effort\"
constant-time operation and embedded-friendly no_std support
"""
license = "Apache-2.0 OR MIT"
notices = [
  "Copyright (c) 2014 Steve \"Sc00bz\" Thomas (steve at tobtu dot com)",
  "Copyright (c) 2021 The RustCrypto Project Developers",
]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/formats/tree/master/base64ct"

[[dependencies]]
name = "block-buffer"
version = "0.10.4"
description = "Buffer type for block processing of data"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2018-2019 The RustCrypto Project Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/utils"

[[dependencies]]
name = "bumpalo"
version = "3.16.0"
description = "A fast bump allocation arena for Rust."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2019 Nick Fitzgerald"]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
repository = "https://github.com/fitzgen/bumpalo"

[[dependencies]]
name = "byte-aes"
version = "0.2.2"
description = "byte-aes is a simple wrapper around the popular aes crate. The goal is to perform Encrypt and Decrypt operations using the Advanced Encryption Standard 256 bit Algorithm conveninent to use instead of use Low level functions of the aes crate"
license = "MIT"

[[dependencies]]
name = "cfg-if"
version = "1.0.0"
description = """
A macro to ergonomically define an item depending on a large number of #[cfg]
parameters. Structured like an if-else chain, the first matching branch is the
item that gets emitted.
"""
license = "MIT/Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
repository = "https://github.com/alexcrichton/cfg-if"

[[dependencies]]
name = "cipher"
version = "0.4.4"
description = "Traits for describing block ciphers and stream ciphers"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2016-2020 RustCrypto Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/traits"

[[dependencies]]
name = "cpufeatures"
version = "0.2.12"
description = """
Lightweight runtime CPU feature detection for aarch64, loongarch64, and x86/x86_64 targets, 
with no_std support and support for mobile targets including Android and iOS
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2020 The RustCrypto Project Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/utils"

[[dependencies]]
name = "crypto-common"
version = "0.1.6"
description = "Common cryptographic traits"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2021 RustCrypto Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/traits"

[[dependencies]]
name = "ctr"
version = "0.9.2"
description = "CTR block modes of operation"
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2018 Artyom Pavlov",
  "Copyright (c) 2018-2022 RustCrypto Developers",
]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/block-modes"

[[dependencies]]
name = "digest"
version = "0.10.7"
description = "Traits for cryptographic hash functions and message authentication codes"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2017 Artyom Pavlov"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/traits"

[[dependencies]]
name = "generic-array"
version = "0.14.7"
description = "Generic types implementing functionality of arrays"
license = "MIT"
notices = ["Copyright (c) 2015 Bartłomiej Kamiński"]
authors = [
  "Bartłomiej Kamiński <fizyk20@gmail.com>",
  "Aaron Trent <novacrazy@gmail.com>",
]
repository = "https://github.com/fizyk20/generic-array.git"

[[dependencies]]
name = "getrandom"
version = "0.2.14"
description = "A small cross-platform library for retrieving random data from system source"
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2014 The Rust Project Developers",
  "Copyright (c) 2018-2024 The rust-random Project Developers",
]
authors = ["The Rand Project Developers"]
repository = "https://github.com/rust-random/getrandom"

[[dependencies]]
name = "ghash"
version = "0.5.1"
description = """
Universal hash over GF(2^128) useful for constructing a Message Authentication Code (MAC),
as in the AES-GCM authenticated encryption cipher.
"""
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2019 RustCrypto Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/universal-hashes"

[[dependencies]]
name = "hmac"
version = "0.12.1"
description = "Generic implementation of Hash-based Message Authentication Code (HMAC)"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2017 Artyom Pavlov"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/MACs"

[[dependencies]]
name = "inout"
version = "0.1.3"
description = "Custom reference types for code generic over in-place and buffer-to-buffer modes of operation."
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2022 Artyom Pavlov",
  "Copyright (c) 2022 The RustCrypto Project Developers",
]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/utils"

[[dependencies]]
name = "js-sys"
version = "0.3.69"
description = """
Bindings for all JS global objects and functions in all JS environments like
Node.js and browsers, built on `#[wasm_bindgen]` using the `wasm-bindgen` crate.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The wasm-bindgen Developers"]
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/js-sys"
homepage = "https://rustwasm.github.io/wasm-bindgen/"

[[dependencies]]
name = "libc"
version = "0.2.153"
description = """
Raw FFI bindings to platform libraries like libc.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014-2020 The Rust Project Developers"]
authors = ["The Rust Project Developers"]
repository = "https://github.com/rust-lang/libc"

[[dependencies]]
name = "log"
version = "0.4.21"
description = """
A lightweight logging facade for Rust
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 The Rust Project Developers"]
authors = ["The Rust Project Developers"]
repository = "https://github.com/rust-lang/log"

[[dependencies]]
name = "once_cell"
version = "1.19.0"
description = "Single assignment cells and lazy values."
license = "MIT OR Apache-2.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/once_cell"

[[dependencies]]
name = "opaque-debug"
version = "0.3.1"
description = "Macro for opaque Debug trait implementation"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2018-2024 The RustCrypto Project Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/utils"

[[dependencies]]
name = "password-hash"
version = "0.5.0"
description = """
Traits which describe the functionality of password hashing algorithms,
as well as a `no_std`-friendly implementation of the PHC string format
(a well-defined subset of the Modular Crypt Format a.k.a. MCF)
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2020-2023 RustCrypto Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/traits/tree/master/password-hash"

[[dependencies]]
name = "pbkdf2"
version = "0.12.2"
description = "Generic implementation of PBKDF2"
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2017 Artyom Pavlov",
  "Copyright (c) 2018-2023 The RustCrypto Project Developers",
]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/password-hashes/tree/master/pbkdf2"

[[dependencies]]
name = "polyval"
version = "0.6.2"
description = """
POLYVAL is a GHASH-like universal hash over GF(2^128) useful for constructing
a Message Authentication Code (MAC)
"""
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2019-2023 RustCrypto Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/universal-hashes"

[[dependencies]]
name = "proc-macro2"
version = "1.0.81"
description = "A substitute implementation of the compiler's `proc_macro` API to decouple token-based libraries from the procedural macro use case."
license = "MIT OR Apache-2.0"
authors = [
  "David Tolnay <dtolnay@gmail.com>",
  "Alex Crichton <alex@alexcrichton.com>",
]
repository = "https://github.com/dtolnay/proc-macro2"

[[dependencies]]
name = "quote"
version = "1.0.36"
description = "Quasi-quoting macro quote!(...)"
license = "MIT OR Apache-2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/quote"

[[dependencies]]
name = "rand_core"
version = "0.6.4"
description = """
Core random number generator traits and tools for implementation.
"""
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2014 The Rust Project Developers",
  "Copyright 2018 Developers of the Rand project",
]
authors = ["The Rand Project Developers", "The Rust Project Developers"]
repository = "https://github.com/rust-random/rand"
homepage = "https://rust-random.github.io/book"

[[dependencies]]
name = "sha2"
version = "0.10.8"
description = """
Pure Rust implementation of the SHA-2 hash function family
including SHA-224, SHA-256, SHA-384, and SHA-512.
"""
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2006-2009 Graydon Hoare",
  "Copyright (c) 2009-2013 Mozilla Foundation",
  "Copyright (c) 2016 Artyom Pavlov",
]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/hashes"

[[dependencies]]
name = "subtle"
version = "2.5.0"
description = "Pure-Rust traits and utilities for constant-time cryptographic implementations."
license = "BSD-3-Clause"
notices = [
  "Copyright (c) 2016-2017 Isis Agora Lovecruft, Henry de Valence. All rights reserved.",
]
authors = [
  "Isis Lovecruft <isis@patternsinthevoid.net>",
  "Henry de Valence <hdevalence@hdevalence.ca>",
]
repository = "https://github.com/dalek-cryptography/subtle"
homepage = "https://dalek.rs/"

[[dependencies]]
name = "syn"
version = "2.0.60"
description = "Parser for Rust source code"
license = "MIT OR Apache-2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/syn"

[[dependencies]]
name = "typenum"
version = "1.17.0"
description = """
Typenum is a Rust library for type-level numbers evaluated at
    compile time. It currently supports bits, unsigned integers, and signed
    integers. It also provides a type-level array of type-level numbers, but its
    implementation is incomplete."""
license = "MIT OR Apache-2.0"
notices = [
  "Copyright (c) 2014 Paho Lurie-Gregg",
  "Copyright 2014 Paho Lurie-Gregg",
]
authors = [
  "Paho Lurie-Gregg <paho@paholg.com>",
  "Andre Bogus <bogusandre@gmail.com>",
]
repository = "https://github.com/paholg/typenum"

[[dependencies]]
name = "unicode-ident"
version = "1.0.12"
description = "Determine whether characters have the XID_Start or XID_Continue properties according to Unicode Standard Annex #31"
license = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
notices = ["Copyright © 1991-2022 Unicode, Inc. All rights reserved."]
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/unicode-ident"

[[dependencies]]
name = "universal-hash"
version = "0.5.1"
description = "Traits which describe the functionality of universal hash functions (UHFs)"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2019-2020 RustCrypto Developers"]
authors = ["RustCrypto Developers"]
repository = "https://github.com/RustCrypto/traits"

[[dependencies]]
name = "version_check"
version = "0.9.4"
description = "Tiny crate to check the version of the installed/running rustc."
license = "MIT/Apache-2.0"
notices = ["Copyright (c) 2017-2018 Sergio Benitez"]
authors = ["Sergio Benitez <sb@sergio.bz>"]
repository = "https://github.com/SergioBenitez/version_check"

[[dependencies]]
name = "wasi"
version = "0.11.0+wasi-snapshot-preview1"
description = "Experimental WASI API bindings for Rust"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
authors = ["The Cranelift Project Developers"]
repository = "https://github.com/bytecodealliance/wasi"

[[dependencies]]
name = "wasm-bindgen"
version = "0.2.92"
description = """
Easy support for interacting between JS and Rust.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The wasm-bindgen Developers"]
repository = "https://github.com/rustwasm/wasm-bindgen"
homepage = "https://rustwasm.github.io/"

[[dependencies]]
name = "wasm-bindgen-backend"
version = "0.2.92"
description = """
Backend code generation of the wasm-bindgen tool
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The wasm-bindgen Developers"]
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/backend"
homepage = "https://rustwasm.github.io/wasm-bindgen/"

[[dependencies]]
name = "wasm-bindgen-macro"
version = "0.2.92"
description = """
Definition of the `#[wasm_bindgen]` attribute, an internal dependency
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The wasm-bindgen Developers"]
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/macro"
homepage = "https://rustwasm.github.io/wasm-bindgen/"

[[dependencies]]
name = "wasm-bindgen-macro-support"
version = "0.2.92"
description = """
The part of the implementation of the `#[wasm_bindgen]` attribute that is not in the shared backend crate
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The wasm-bindgen Developers"]
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/macro-support"
homepage = "https://rustwasm.github.io/wasm-bindgen/"

[[dependencies]]
name = "wasm-bindgen-shared"
version = "0.2.92"
description = """
Shared support between wasm-bindgen and wasm-bindgen cli, an internal
dependency.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The wasm-bindgen Developers"]
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/shared"
homepage = "https://rustwasm.github.io/wasm-bindgen/"

[[dependencies]]
name = "web-sys"
version = "0.3.69"
description = """
Bindings for all Web APIs, a procedurally generated crate from WebIDL
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The wasm-bindgen Developers"]
repository = "https://github.com/rustwasm/wasm-bindgen/tree/master/crates/web-sys"
homepage = "https://rustwasm.github.io/wasm-bindgen/web-sys/index.html"

[[dependencies]]
name = "zeroize"
version = "1.7.0"
description = """
Securely clear secrets from memory with a simple trait built on
stable Rust primitives which guarantee memory is zeroed using an
operation will not be 'optimized away' by the compiler.
Uses a portable pure Rust implementation that works everywhere,
even WASM!
"""
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2018-2021 The RustCrypto Project Developers"]
authors = ["The RustCrypto Project Developers"]
repository = "https://github.com/RustCrypto/utils/tree/master/zeroize"
